# options
set-option global tabstop 4
set-option global indentwidth 4

# map global insert <tab> <space><space><space><space>
hook global InsertChar \t %{ exec -draft h@ }
map global insert <s-tab> '<a-;><lt>'

set-option global scrolloff 8,3

set-option global startup_info_version -1

add-highlighter global/numlines number-lines -relative -hlcursor -separator " "
add-highlighter global/column80 column 80 default,rgb:373c47

# file callbacks

hook global BufSetOption filetype=ocaml %{
    set-option buffer tabstop 2
    set-option buffer indentwidth 2
}

hook global BufSetOption filetype=markdown %{
    add-highlighter buffer/ regex '\[([^\n]*?)\]\(([^\n]*?)\)' 0:mdlink 2:link
    add-highlighter buffer/ regex "\[x\]" 0:green
    notes
}

# notes
define-command notes %{
    map buffer insert <tab> '<a-;><gt>'
    remove-highlighter global/column80
    add-highlighter buffer/column100 column 100 default,rgb:373c47
    enable-smoothwrap
    set-option buffer tabstop 2
    set-option buffer indentwidth 2
}

# mappings
map global user y "<a-|>wl-copy<ret>" -docstring "yank to clipboard"
map global user p "<a-!>wl-paste -n<ret>" -docstring "paste from clipboard"
map global user P "!wl-paste -n<ret>" -docstring "paste in front from clipboard"

map global normal "/" "/(?i)"
map global normal "#" ":comment-line<ret>"

map global goto x "<esc><a-|>xargs xdg-open<ret>" -docstring "follow url"

map global goto n "<esc>:grep-next-match<ret>"
map global goto p "<esc>:grep-previous-match<ret>"

# plugins
source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload

# fuzzy search
plug "andreyorst/fzf.kak" config %{
    map global user f ":fzf-mode<ret>f" -docstring "find file"
    map global user g ":fzf-mode<ret>g" -docstring "grep string"
    map global user b ":fzf-mode<ret>b" -docstring "find buffer"
    map global user s ":fzf-mode<ret>" -docstring "fzf mode"
} defer fzf-file %{
    set-option global fzf_file_command "fd"
    set-option global fzf_highlight_command "bat --color=always --theme=Coldark-Dark --style=plain {}"
} defer fzf-grep %{
    set-option global fzf_grep_command "rg"
    set-option global fzf_grep_preview_command "bat --color=always --theme=Coldark-Dark --style=plain --highlight-line {2} {1}"
}

define-command fuzzy_find -docstring "fuzzy search file" -params 1 %{ edit %arg{1} }
complete-command fuzzy_find shell-script-candidates %{ fd --type f }

set-option global grepcmd "rg -n"

# auto pairs
plug "alexherbo2/auto-pairs.kak"
enable-auto-pairs

# lsp
eval %sh{kak-lsp}
lsp-enable

remove-hooks global lsp-filetype-python

hook -group lsp-filetype-python global BufSetOption filetype=python %{
    set-option buffer lsp_servers %{
        [pyright-langserver]
        root_globs = ["requirements.txt", "setup.py", "pyproject.toml", "pyrightconfig.json", ".git", ".hg"]
        args = ["--stdio"]
    }
}

map global user l ":enter-user-mode lsp<ret>" -docstring "LSP mode"

# smooth wrapping
plug "grownplanet/smoothwrap.kak" config %{
    set-option global wrap_width 100
}

# colorscheme at the end so it overwrites all the colors
colorscheme onedark
