# options
set-option global tabstop 4
set-option global indentwidth 4
map global insert <tab> <space><space><space><space>

set-option global scrolloff 8,3

set-option global startup_info_version -1

add-highlighter global/ number-lines -relative -hlcursor -separator " "
add-highlighter global/ column 80 default,rgb:494d64

hook global BufSetOption filetype=ocaml %{
    set-option global tabstop 2
    set-option global indentwidth 2
    map global insert <tab> <space><space>
}

hook global BufSetOption filetype=markdown %{
    add-highlighter buffer/ regex '\[([^\n]*?)\]\(([^\n]*?)\)' 0:mdlink 2:link
    add-highlighter buffer/ regex "\[x\]" 0:green
    add-highlighter buffer/ regex "DONE" 0:green
    add-highlighter buffer/ regex "WONTDO" 0:red
    add-highlighter buffer/ regex "TODO" 0:yellow
}

# mappings
map global user y "<a-|>wl-copy<ret>" -docstring "yank to clipboard"
map global user p "<a-!>wl-paste<ret>" -docstring "paste from clipboard"
map global user u "<a-|>xargs xdg-open<ret>" -docstring "follow url"

map global normal "/" "/(?i)"

map global normal "#" ":comment-line<ret>"

# plugins
source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload

# fzf
plug "andreyorst/fzf.kak" config %{
    map global user f ":fzf-mode<ret>f" -docstring "find file"
    map global user g ":fzf-mode<ret>g" -docstring "grep string"
    map global user b ":fzf-mode<ret>b" -docstring "find buffer"
    map global user s ":fzf-mode<ret>" -docstring "fzf mode"
} defer fzf-file %{
    set-option global fzf_file_command "fd"
    set-option global fzf_highlight_command "bat --color=always --theme=Coldark-Dark --style=plain {}"
} defer fzf-grep %{
    set-option global fzf_grep_command "rg"
    set-option global fzf_grep_preview_command "bat --color=always --theme=Coldark-Dark --style=plain --highlight-line {2} {1}"
}

# auto pairs
plug "alexherbo2/auto-pairs.kak"
enable-auto-pairs

# lsp
eval %sh{kak-lsp}
lsp-enable

map global user l ":enter-user-mode lsp<ret>" -docstring "LSP mode"

# smooth wrapping
plug "grownplanet/smoothwrap.kak" config %{
    set-option global wrap_width 80
}

# colorscheme at the end so it overwrites all the colors
colorscheme catppuccin_macchiato
