theme = "onedark"

[editor]
# rulers = [100]
idle-timeout = 0
mouse = false
midle-click_paste = false
bufferline = "always"
cursorline = true


# line-ending = "lf"

# [editor.statusline]
# line-ending = "crlf"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
select = "block"
normal = "underline"

