# only on windows
# shell = "nu.exe"

# Colors (One Dark)

# Default colors
[colors.primary]
background = '#282c34'
foreground = '#abb2bf'

# Normal colors
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'

[cursor.style]
shape = "underline"

[font.normal]
family = "hack nerd font"
# family = "comicshannsmono nerd font"

[window]
dimensions = { columns = 120, lines = 35 }
opacity = 0.9
title = "Alacritty :)"

[window.padding]
x = 8
y = 8
